export function randomQuestion() {
  return Questions[Math.trunc(Math.random() * Questions.length)];
}

export function isCorrectAnswer(question, answer) {
  return question.correct_answer[answer + "_correct"] === "true";
}

const Questions = [
  {
    id: 667,
    question: "Choose the odd one out.",
    description: null,
    answers: {
      answer_a: "csh",
      answer_b: "bsh",
      answer_c: "ksh",
      answer_d: "Kernel",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation:
      "Kernel is the core part of the OS and is odd one the rest are popular shells.",
    tip: null,
    tags: [{ name: "BASH" }],
    category: "Linux",
    difficulty: "Easy",
  },
  {
    id: 696,
    question:
      "Which command can be used to execute a command/s repeatedly for the given schedule?",
    description: null,
    answers: {
      answer_a: "crontab",
      answer_b: "while",
      answer_c: "for",
      answer_d: "set",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [{ name: "BASH" }, { name: "Linux" }],
    category: "Linux",
    difficulty: "Medium",
  },
  {
    id: 752,
    question:
      "How will you pass and access arguments to a script in Linux/Bash?",
    description: null,
    answers: {
      answer_a:
        "scriptName \u201cArg1\u201d \u201cArg2\u201d\u2026.\u201dArgn\u201d and can be accessed inside the script as $1 , $2 .. $n.",
      answer_b:
        "scriptName -arg \u201cArg1\u201d \u201cArg2\u201d\u2026.\u201dArgn\u201d and can be accessed inside the script as $1 , $2 .. $n.",
      answer_c:
        'scriptName "Arg1 Arg2\u2026.Argn\u201d and can be accessed inside the script as $1 , $2 .. $n.',
      answer_d:
        "scriptName \u201cArg1\u201d \u201cArg2\u201d\u2026.\u201dArgn\u201d and can be accessed inside the script as $Arg1 , $Arg2 .. $Argn.",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "BASH" }],
    category: "Linux",
    difficulty: "Medium",
  },
  {
    id: 744,
    question: "How to mark a node called my-node as schedulable in Kubernetes?",
    description: null,
    answers: {
      answer_a: "kubectl schedulable my-node",
      answer_b: "kubectl up my-node",
      answer_c: "kubectl available my-node",
      answer_d: "kubectl uncordon my-node",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "Kubernetes" }],
    category: "Linux",
    difficulty: "Medium",
  },
  {
    id: 655,
    question: "Which command can be used to find a word from a text file?",
    description: null,
    answers: {
      answer_a: "cut",
      answer_b: "sort",
      answer_c: "find",
      answer_d: "grep",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "BASH" }],
    category: "Linux",
    difficulty: "Easy",
  },
  {
    id: 702,
    question:
      "Which command can be used to display basic information about your server?",
    description: null,
    answers: {
      answer_a: "uname",
      answer_b: "info",
      answer_c: "ls",
      answer_d: "show",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [{ name: "Linux" }],
    category: "Linux",
    difficulty: "Easy",
  },
  {
    id: 28,
    question: "Where is Linux user list stored?",
    description: null,
    answers: {
      answer_a: "/etc/users",
      answer_b: "/usr/local/users",
      answer_c: "By running the command show users",
      answer_d: "None of the above.",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_d",
    explanation: null,
    tip: null,
    tags: [{ name: "Linux" }],
    category: "Linux",
    difficulty: "Medium",
  },
  {
    id: 1071,
    question: "From which file does the command `free` takes it's information",
    description: null,
    answers: {
      answer_a: "/proc/meminfo",
      answer_b: "/proc/freemem",
      answer_c: "/proc/memfree",
      answer_d: "/dev/meminfo",
      answer_e: "/dev/freemem",
      answer_f: "/dev/memfree",
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [{ name: "Linux" }],
    category: "Linux",
    difficulty: "Easy",
  },
  {
    id: 691,
    question: "Which operator can be used to throw a process into background?",
    description: null,
    answers: {
      answer_a: "&",
      answer_b: "&&",
      answer_c: "|",
      answer_d: "||",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [{ name: "BASH" }],
    category: "Linux",
    difficulty: "Easy",
  },
  {
    id: 645,
    question:
      "How can we find the process name from its process id? Assume the Proccess ID is 1",
    description: null,
    answers: {
      answer_a: "ps \u2013p 1",
      answer_b: "find 1",
      answer_c: "top 1",
      answer_d: "get 1",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "BASH" }],
    category: "Linux",
    difficulty: "Easy",
  },
];
